[package]
name = "window-hider"
version = "0.1.0"
authors = ["Perry Nguyen <pfnguyen@hanhuy.com>"]

[dependencies]
winapi="0.2.8"
user32-sys="0.1.1"
kernel32-sys="0.1.4"
gdi32-sys="0.1.1"
comctl32-sys="0.2.0"
